# Site settings
title: maikhel
email: mlecicki@live.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://maikhel.github.io"
greeting: "Hello There!"

homeurl: "/index"
gallery_page: "/gallery"
about_page: "/about"
twitter:
  username: mlecicki
  card: summary

social:
  name: Michał Łęcicki
  links:
    - https://twitter.com/mlecicki
    - https://www.linkedin.com/in/maikhel
    - https://github.com/maikhel
    - https://stackoverflow.com/users/8893167/maikhel

paginate: 5
paginate_path: "/posts/:num/"
plugins:
  - jekyll-paginate
  - jekyll-turbo
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: "photos"
    values:
      image: true
  - scope:
      path: "photos/beskid"
    values:
      image: false

# Build settings
markdown: kramdown
