title: "Maikhel’s Blog"
description: "Ruby developer writing about refactoring, maintainable code, and engineering practices."
email: mlecicki@live.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://maikhel.github.io"
author:
  name: Maikhel

homeurl: "/index"
permalink: /blog/:title/
social:
  name: Michał Łęcicki
  links:
    - https://twitter.com/mlecicki
    - https://www.linkedin.com/in/maikhel
    - https://github.com/maikhel
    - https://stackoverflow.com/users/8893167/maikhel

collections:
  talks:
    output: true
    permalink: /talks/:name/

plugins:
  - jekyll-turbo
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
